---
title: "Representacion 1"
author: "Fanfan Yang"
date: "30/11/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
if(!require(ggplot2)){
    install.packages('ggplot2', repos='http://cran.us.r-project.org')
    library(ggplot2)
}
if(!require(grid)){
  install.packages('grid',repos='http://cran.us.r-project.org')
  library(grid)
}
if(!require(gridExtra)){
  install.packages('gridExtra', repos='http://cran.us.r-project.org')
  library(gridExtra)
}

```
```{r}
df <- read.csv("./StudentsPerformance.csv", header = TRUE, sep = ",")
```

```{r}
dim(df)
```

```{r}
str(df)
```

```{r}
missing <- df[is.na(df),]
dim(missing)
```
```{r}
colSums(is.na(df))
```
```{r}
colSums(df=="")
```

```{r}
g1<-hist(df$math.score, col = "#3182bd", main="Student performance in Math exam", xlab="Marks", ylab="Number of students")
```
```{r}
g2<-hist(df$reading.score, col = "#9ecae1", main="Student performance in Reading exam", xlab="Marks", ylab="Number of students")
```
```{r}
g3<-hist(df$reading.score, col = "#deebf7", main="Student performance in Writing exam", xlab="Marks", ylab="Number of students")
```

